export const PAYMENT_STATUS_PENDING = "pending";
export const PAYMENT_STATUS_IN_PROCESS = "in_process";
export const PAYMENT_STATUS_APPROVED = "approved";
export const PAYMENT_STATUS_REJECTED = "rejected";
export const PAYMENT_STATUS_CANCELLED = "cancelled";
export const PAYMENT_STATUS_REFUNDED = "refunded";
export const PAYMENT_STATUS_CHARGED_BACK = "charged_back";

export const PAYMENT_STATUSES = [
  PAYMENT_STATUS_PENDING,
  PAYMENT_STATUS_IN_PROCESS,
  PAYMENT_STATUS_APPROVED,
  PAYMENT_STATUS_REJECTED,
  PAYMENT_STATUS_CANCELLED,
  PAYMENT_STATUS_REFUNDED,
  PAYMENT_STATUS_CHARGED_BACK,
];

export const MERCADO_PAGO_PROVIDER = "mercado_pago";
export const CURRENCY_ARS = "ARS";
